### PR TITLE
Adds a vector class 

### PR DESCRIPTION
**Pull request by josephsweeney**
This implements all the agreed upon features that a vector should have. For issue #7.

### CODE REVIEW

**Comment by DrewMonroe** [comment]
Line 36, p is undefined

**Comment by josephsweeney** [comment]
rip copy paste. force pushing a fix real fast.

**Comment by DrewMonroe** [comment]
- For vector subtraction, the return value should probably be a `Vector` no? Currently returns a `numpy array`. Same with addition and `lift()`. Should be an easy fix. 
- I get an error when doing scalar multiplication, unsupported operand
- Should doing `Vector(1,2,3) * Vector(1,2,3)` be the dot product? Currently multiplies each of the components of the vector, but maybe that's what we wanted? Also, if we do want to multiply the components, then like the first bullet, it should probably return a `Vector`
- Using the `norm_squared` function returns a float that has floating point fuzziness. However, the dot product is fine. Maybe switch the `norm_squared` function to use the same code as `dot`

**Comment by DrewMonroe** [comment]
Line 2: unused import
Line 56: `else if` should be `elif`

**Comment by josephsweeney** [comment]
shit.

**Comment by DrewMonroe** [comment]
Don't hate me plz

**Comment by josephsweeney** [comment]
fixed lol

**Comment by DrewMonroe** [comment]
Aside from the unused import on `line 2`, I'm happy

**Comment by josephsweeney** [comment]
ill fix that real quick.

**Comment by DrewMonroe** [comment]
You da best

**Comment by DrewMonroe** [comment]
Actually, wait, scalar multiplication still doesn't work I think

**Comment by DrewMonroe** [comment]
Ahh, so it works if you do `Vector(1, 2, 3) * 3` but not if you do `3 * Vector(1, 2, 3)`

**Comment by josephsweeney** [comment]
Oh i didn't realize lemme invesitgate

**Comment by saileshsimhadri** [comment]
you have to have a **rmult** method

**Comment by saileshsimhadri** [comment]
that should fix that

**Comment by DrewMonroe** [comment]
@saileshsimhadri coming in clutch. assuming he's right

**Comment by saileshsimhadri** [comment]
Im pretty sure you can just say **rmult**=**mult** and it should fix the problem

**Comment by josephsweeney** [comment]
oh okay ill adjust that, fixed it before looking at your responses.

**Comment by DrewMonroe** [comment]
So interestingly enough, @josephsweeney original multiplication worked (well aside from the fact that it didn't return a `Vector`). Commit 20a8ba25ad92c3a9fdf41dac6ffa1d857d49c68b has the original code, so we could move the `__mult__` back to what it was in that commit. Also, are the rest of the `__r__` methods needed, since they will only be done on two `Vectors`?

**Comment by josephsweeney** [comment]
Yeah i just realized they were redundant.

**Comment by josephsweeney** [comment]
I think I have it in the state we want it to be in.

**Review by DrewMonroe — APPROVED** [review]

**Pull request merged**
