### PR TITLE
Implemented some basic stuff using numpy for vectors.

### PR DESCRIPTION
**Pull request by Byvire**
We now have incircle and counterclockwise predicates. I can't
promise that they work, but we certainly have them.

### CODE REVIEW

**Review by josephsweeney — COMMENTED** [review]
This seems like a solid jumping off point where we can refine from. I'll let @DrewMonroe or @saileshsimhadri look as well for final approval but i figure any cleaning up can be done by someone other than Oliver so we also have some work to do.

**Comment by josephsweeney** [comment]
Oh and in the future we should probably keep all our branches in the same repo instead of forking, or at least give your forked branch a descriptive name to historic purposes.

**Comment by DrewMonroe** [comment]
Is there a reason why incircle takes in a variable amount of arguments? Shouldn't it only take 4, where the first 3 define the circle and the last is the point either inside the circle or outside the circle, or is there something more with this function?

**Comment by Byvire** [comment]
`incircle` takes a variable number of arguments because I suspect that Dr. Sheehy will tell us the same test is useful in higher dimensions, similarly to `ccw`.

As far as branching instead of forking, I tend to agree. However, I'm not aware of a way to make a pull request without forking, and I'm not currently listed as a collaborator.

For the record, the stuff in test.py is not useful except as documentation of what I was thinking. The tests in predicates.main are not sufficient, and also that's not how testing ought to be done (as you've pointed out).

**Comment by DrewMonroe** [comment]
Ah okay I see what you're saying about incircle, sorry I wasn't thinking about it that way. Good call. I'll merge and someone can work on unit tests

**Review by DrewMonroe — APPROVED** [review]

**Pull request merged**
