### PR TITLE
fixed ccw

### PR DESCRIPTION
**Pull request by josephsweeney**
Issue #9

### CODE REVIEW

**Comment by DrewMonroe** [comment]
Do we want to remove the old stuff from this file that isn't relevant anymore, like `vector()` and such?

**Comment by josephsweeney** [comment]
sure i'll add a commit for that

**Review by saileshsimhadri — APPROVED** [review]

**Comment by josephsweeney** [comment]
get rid of `lift_matrix()`?

**Comment by saileshsimhadri** [comment]
yeah. We don't need it

**Comment by DrewMonroe** [comment]
I think this PR is fine, only think is I think I remember @Byvire mentioning something about a different sign test, but we can change that later

**Comment by josephsweeney** [comment]
yeah i just went with what is quick.

**Pull request merged**
